const fs = require('fs')
const path = require('path')

const src = path.join('C:/Users/mrcry/Downloads/liquidity-radar', 'index.html')
const out = path.join(
  'C:/Users/mrcry/Downloads/liquidity-radar/liquidity-radar-react/src/components',
  'Shell.tsx',
)

const html = fs.readFileSync(src, 'utf8')

const bodyStart = html.indexOf('<header class="top">')
const scriptIdx = html.lastIndexOf('<script>')
if (bodyStart < 0 || scriptIdx < 0) throw new Error('bounds not found')
let frag = html.slice(bodyStart, scriptIdx)

// --- boolean / camelCase attribute names (React requires the JS DOM casing) ---
frag = frag
  .replace(/autocomplete=/g, 'autoComplete=')
  .replace(/maxlength=/g, 'maxLength=')
  .replace(/tabindex=/g, 'tabIndex=')
  .replace(/readonly=/g, 'readOnly=')
  .replace(/contenteditable=/g, 'contentEditable=')
  .replace(/spellcheck=/g, 'spellCheck=')
  .replace(/inputmode=/g, 'inputMode=')

// --- class -> className ---
frag = frag.replace(/\sclass="/g, ' className="').replace(/\sclass='/g, " className='")

// --- self-close void elements (must run BEFORE event conversion, which injects '>' inside attrs) ---
frag = frag.replace(
  /<((?:input|img|br|hr|meta|link|embed|source|track|wbr)\b[^>]*?)(?<!\/)>/g,
  '<$1 />',
)

// --- style="k:v;k2:v2" -> style={{ k: 'v', k2: 'v2' }} (React needs object) ---
const styleToObj = (css) => {
  const o = {}
  for (let part of css.split(';')) {
    part = part.trim()
    if (!part) continue
    const ci = part.indexOf(':')
    if (ci < 0) continue
    const k = part
      .slice(0, ci)
      .trim()
      .replace(/-([a-z])/g, (_, c) => c.toUpperCase())
    o[k] = part.slice(ci + 1).trim()
  }
  return (
    '{ ' +
    Object.entries(o)
      .map(([k, v]) => `'${k}': '${v.replace(/'/g, "\\'")}'`)
      .join(', ') +
    ' }'
  )
}
frag = frag.replace(/\sstyle="([^"]*)"/g, (m, css) => ' style={' + styleToObj(css) + '}')

// --- number-valued props: maxLength={n} ---
frag = frag.replace(/\smaxLength="(\d+)"/g, ' maxLength={$1}')

// --- minified handler-name mangle inside event attribute JS only ---
const hNames = [
  'switchSigMode',
  'onSigSearch',
  'analyzeSigCoin',
  'closeModal',
  'addPosition',
  'addAlert',
  'enableAlerts',
]
const mangleJs = (js) => {
  let s = js
  s = s.replace(/\$\s*\(/g, 'w.$(')
  for (const n of hNames) s = s.replace(new RegExp('\\b' + n + '\\b', 'g'), 'w.' + n)
  return s
}

// --- convert onclick="..." -> onClick={...} (mangled) ---
frag = frag.replace(/onclick="([^"]*)"/g, (m, js) => {
  const body = mangleJs(js).trim()
  let arg = '()'
  let inner = body
  if (/event|this\b|\.value/.test(body) || body.includes('=>')) {
    arg = '(e)'
    inner = body
      .replace(/\bevent\b/g, 'e')
      .replace(/\bthis\.value\b/g, 'e.currentTarget.value')
      .replace(/===this/g, '=== e.currentTarget')
  }
  return `onClick={${arg} => { ${inner} }}`.replace('{ }', '{}')
})

// --- oninput="..." -> onInput={...} ---
frag = frag.replace(/oninput="([^"]*)"/g, (m, js) => {
  const body = mangleJs(js)
    .trim()
    .replace(/\bthis\.value\b/g, 'e.currentTarget.value')
  return `onInput={(e) => { ${body} }}`.replace('{ }', '{}')
})

// --- onkeydown="..." -> onKeyDown={...} ---
frag = frag.replace(/onkeydown="([^"]*)"/g, (m, js) => {
  const body = mangleJs(js)
    .trim()
    .replace(/\bevent\b/g, 'e')
    .replace(/\bthis\.value\b/g, 'e.currentTarget.value')
  return `onKeyDown={(e) => { ${body} }}`.replace('{ }', '{}')
})

function indent(s, n) {
  const pad = ' '.repeat(n)
  return s
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n')
}

const outText = `// Liquidity Radar — React shell DOM (Phase 1 migration).
// Mechanical 1:1 port of the original index.html body. Ids/classes/palette
// are preserved verbatim so the engine (src/engine) can drive the tree
// exactly as in the vanilla app. Regenerated by scripts/html2jsx.cjs from
// the original index.html — do not hand-edit; App.tsx consumes <Shell/>.
const w = window as any

export function Shell() {
  return (
    <>
${indent(frag, 6)}
    </>
  )
}
`
fs.writeFileSync(out, outText)
console.log('wrote', out, frag.split('\n').length, 'lines of JSX')
