import type { CoinMeta } from '../types/market'

export const COINS: Record<string, CoinMeta> = {
  BTC: { sym: 'BTCUSDT', name: 'Bitcoin', icon: '₿', color: '#F7931A' },
  ETH: { sym: 'ETHUSDT', name: 'Ethereum', icon: '◆', color: '#627EEA' },
  SOL: { sym: 'SOLUSDT', name: 'Solana', icon: '◎', color: '#9945FF' },
  BNB: { sym: 'BNBUSDT', name: 'BNB', icon: '⬡', color: '#F3BA2F' },
  DOGE: { sym: 'DOGEUSDT', name: 'Dogecoin', icon: 'D', color: '#C2A633' },
  XRP: { sym: 'XRPUSDT', name: 'XRP', icon: '✕', color: '#25A0E0' },
  ADA: { sym: 'ADAUSDT', name: 'Cardano', icon: '🔹', color: '#0033AD' },
  AVAX: { sym: 'AVAXUSDT', name: 'Avalanche', icon: '🔺', color: '#E84142' },
  DOT: { sym: 'DOTUSDT', name: 'Polkadot', icon: '⚪', color: '#E6007A' },
  LINK: { sym: 'LINKUSDT', name: 'Chainlink', icon: '🔗', color: '#2A5ADA' },
  UNI: { sym: 'UNIUSDT', name: 'Uniswap', icon: '🦄', color: '#FF007A' },
  TRUMP: { sym: 'TRUMPUSDT', name: 'OFFICIAL TRUMP', icon: '🎩', color: '#D4AF37' },
  PEPE: { sym: 'PEPEUSDT', name: 'Pepe', icon: 'P', color: '#4CAF50' },
  WIF: { sym: 'WIFUSDT', name: 'dogwifhat', icon: '🧢', color: '#C08A53' },
  FLOKI: { sym: 'FLOKIUSDT', name: 'Floki', icon: 'F', color: '#E6B800' },
  SHIB: { sym: 'SHIBUSDT', name: 'Shiba Inu', icon: 'S', color: '#FFA409' },
  BONK: { sym: 'BONKUSDT', name: 'Bonk', icon: '🔨', color: '#FF6600' },
  POL: { sym: 'POLUSDT', name: 'Polygon', icon: '⬢', color: '#8247E5' },
  ARB: { sym: 'ARBUSDT', name: 'Arbitrum', icon: '🔄', color: '#28A0F0' },
  OP: { sym: 'OPUSDT', name: 'Optimism', icon: '🔴', color: '#FF0420' },
  SUI: { sym: 'SUIUSDT', name: 'Sui', icon: '💧', color: '#4DA2FF' },
  APT: { sym: 'APTUSDT', name: 'Aptos', icon: '🌀', color: '#6FDBC2' },
  NEAR: { sym: 'NEARUSDT', name: 'NEAR Protocol', icon: 'N', color: '#00C1DE' },
  FIL: { sym: 'FILUSDT', name: 'Filecoin', icon: '📦', color: '#0090FF' },
  AAVE: { sym: 'AAVEUSDT', name: 'Aave', icon: '👻', color: '#B6509E' },
  MKR: { sym: 'MKRUSDT', name: 'Maker', icon: '🧱', color: '#1AAB9B' },
  INJ: { sym: 'INJUSDT', name: 'Injective', icon: '💉', color: '#00BFFF' },
  TIA: { sym: 'TIAUSDT', name: 'Celestia', icon: 'T', color: '#7B2BF9' },
  SEI: { sym: 'SEIUSDT', name: 'Sei', icon: '🌊', color: '#9E1F19' },
}

export const TOP16 = [
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'DOGE',
  'XRP',
  'ADA',
  'AVAX',
  'DOT',
  'LINK',
  'UNI',
  'TRUMP',
  'PEPE',
  'WIF',
  'FLOKI',
  'SHIB',
]

export const CELEBS = ['TRUMP', 'DOGE', 'PEPE', 'WIF', 'FLOKI', 'SHIB', 'BONK']

export const TICKER_COINS = [
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'DOGE',
  'XRP',
  'ADA',
  'TRUMP',
  'PEPE',
  'WIF',
]

export const COIN_ALIASES: Record<string, string[]> = {
  BTC: ['bitcoin', 'btc', 'btcusdt', 'satoshi', 'digital gold', 'xapo'],
  ETH: ['ethereum', 'eth', 'ether', 'ethusdt', 'vitalik', 'buterin'],
  SOL: ['solana', 'sol', 'solusdt'],
  BNB: ['bnb', 'binance coin', 'binance', 'bsc', 'binance smart chain'],
  DOGE: ['dogecoin', 'doge'],
  XRP: ['xrp', 'ripple'],
  ADA: ['cardano', 'ada'],
  AVAX: ['avalanche', 'avax'],
  DOT: ['polkadot', 'dot'],
  LINK: ['chainlink', 'link'],
  UNI: ['uniswap', 'uni'],
  POL: ['polygon', 'matic', 'pol'],
  TRUMP: [
    'trump',
    'trumpcoin',
    'donald',
    'maga',
    'officialtrump',
    'official trump',
    'trump coin',
    'donald trump',
  ],
  PEPE: ['pepe', 'peppe', 'peppy', 'pepecoin', 'pepe coin'],
  WIF: ['dogwifhat', 'wif', 'dogwithhat', 'wifhat', 'dog wif hat', 'dogwif'],
  FLOKI: ['floki', 'flokiinu', 'floki inu'],
  SHIB: ['shiba', 'shib', 'shibainu', 'shiba inu', 'shiba inu token'],
  BONK: ['bonk', 'bonkcoin', 'bonk coin'],
  ARB: ['arbitrum', 'arb'],
  OP: ['optimism', 'op'],
  SUI: ['sui'],
  APT: ['aptos', 'apt'],
  NEAR: ['near protocol', 'near'],
  FIL: ['filecoin', 'fil'],
  AAVE: ['aave'],
  MKR: ['maker', 'mkr'],
  INJ: ['injective', 'inj'],
  TIA: ['celestia', 'tia'],
  SEI: ['sei network', 'sei'],
  NEIRO: ['neiro', 'neirocoin', 'neiro eth'],
  TREMP: ['tremp', 'meme of trump', 'dark maga'],
}
