// Liquidity Radar — React shell DOM (Phase 1 migration).
// Mechanical 1:1 port of the original index.html body. Ids/classes/palette
// are preserved verbatim so the engine (src/engine) can drive the tree
// exactly as in the vanilla app. Regenerated by scripts/html2jsx.cjs from
// the original index.html — do not hand-edit; App.tsx consumes <Shell/>.
import { CoinSearchWidget } from './search/CoinSearchWidget'
import { TimeframePicker } from './chart/TimeframePicker'
import { LayoutPicker } from './chart/LayoutPicker'
import { IndicatorPicker } from './chart/IndicatorPicker'
import { ReplayBar, ReplayButton } from './chart/ReplayBar'
import { CoinPicker } from './chart/CoinPicker'
import { WhaleLegend } from './chart/WhaleLegend'
import { ChartStylePicker } from './chart/ChartStylePicker'
import { lazy, Suspense } from 'react'
const LiqHeatmap = lazy(() => import('./analysis/LiqHeatmap').then((m) => ({ default: m.LiqHeatmap })))
const CrossExchangeTable = lazy(() =>
  import('./analysis/CrossExchangeTable').then((m) => ({ default: m.CrossExchangeTable })),
)
import { DrawToolPicker } from './chart/DrawToolPicker'
import { OverlayTogglePicker } from './chart/OverlayTogglePicker'
import { ConfluencePanel } from './chart/ConfluencePanel'
import { OBImbalanceGauge } from './chart/OBImbalanceGauge'
import { DivergenceBanner } from './chart/DivergenceBanner'
const MLPredictionPanel = lazy(() =>
  import('./chart/MLPredictionPanel').then((m) => ({ default: m.MLPredictionPanel })),
)
const RLPolicyPanel = lazy(() =>
  import('./chart/RLPolicyPanel').then((m) => ({ default: m.RLPolicyPanel })),
)
const NeuralNetPage = lazy(() =>
  import('./chart/NeuralNetViz').then((m) => ({ default: m.NeuralNetPage })),
)
const BubblesCanvas = lazy(() =>
  import('./BubblesCanvas').then((m) => ({ default: m.BubblesCanvas })),
)
import { renderAlerts } from '../features/alerts/alerts'
import { openModal } from '../utils/dom'
import { ChartSidePanel } from './chart/ChartSidePanel'
import { Footer } from './footer/Footer'
import { DashHead } from './DashHead'
import { Sidebar } from './Sidebar'
import { HOT_LIST } from '../constants/market'
import { Guard } from './ErrorBoundary'
import { HomeDashboard } from './HomeDashboard'
const SettingsPage = lazy(() => import('./SettingsPage').then((m) => ({ default: m.SettingsPage })))
const AiAssistant = lazy(() => import('./chat/AiAssistant').then((m) => ({ default: m.AiAssistant })))
const EconomicCalendar = lazy(() =>
  import('./news/EconomicCalendar').then((m) => ({ default: m.EconomicCalendar })),
)
import { useEffect, useRef } from 'react'
const w = window as any

export function Shell() {
  // Pro Terminal embed — the iframe src is only set once the Pro tab becomes
  // visible (IntersectionObserver) so the embedded app's streams don't run in
  // the background while the user is on another tab. Dev serves pro-terminal on
  // :5174; production serves the pre-built /pro/ assets from the same deploy.
  const proRef = useRef<HTMLIFrameElement>(null)
  useEffect(() => {
    const PRO_SRC = (import.meta as any).env?.DEV ? 'http://localhost:5174' : '/pro/'
    const el = proRef.current
    const tab = document.getElementById('tab-pro')
    if (!el || !tab) return
    const obs = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting) { el.src = PRO_SRC; obs.disconnect() }
    }, { threshold: 0 })
    obs.observe(tab)
    return () => obs.disconnect()
  }, [])

  return (
    <>
      <Sidebar />
      <header className="top">
        <div className="top-inner">
          <div className="logo"><span className="dish">📡</span><span className="logo-text"><b>LIQUIDITY</b>&nbsp;RADAR</span></div>
          <div style={{ 'display': 'flex', 'alignItems': 'center', 'gap': '8px' }}>
            <button className="theme-btn" id="alertBtn" title="Price alerts (desktop notifications)" style={{ 'fontSize': '13px', 'fontWeight': '800', 'fontFamily': 'var(--mono)' }} onClick={() => { renderAlerts(); openModal('alModal') }}>AL</button>
            <button className="theme-btn" id="paletteBtn" title="Color themes / palettes" style={{ 'fontSize': '15px', 'fontWeight': '800' }}>🎨</button>
            <button className="theme-btn" id="themeBtn" title="Toggle dark/light mode" style={{ 'fontSize': '12px', 'fontWeight': '800', 'fontFamily': 'var(--mono)' }}>D</button>
            <div className="status-pill" id="statusPill"><span className="dot"></span><span id="statusTxt">Try</span></div>
          </div>
        </div>
        <div className="tickerbar"><div className="ticker-track" id="tickerTrack"></div></div>
      </header>
      
      <CoinSearchWidget />
      
      <div className="container">
      <main>
      
      <section className="tab-section active" id="tab-home">
        <DashHead zone="overview" name="Dashboard" sub="Every section at a glance — open one to go deeper" />
        <Guard name="Dashboard"><HomeDashboard /></Guard>
      </section>

      <section className="tab-section" id="tab-radar">
        <DashHead zone="overview" name="Overview" sub="Live price, derivatives and momentum at a glance" />
        <div className="card hero-card">
          <div className="hero-main">
            <div className="hero-id">
              <div className="hero-icon" id="heroIcon">₿</div>
              <div>
                <div className="hero-name" id="heroName">Bitcoin</div>
                <div className="hero-pair" id="heroPair">BTCUSDT · BINANCE SPOT</div>
              </div>
            </div>
            <div className="hero-price-block">
              <div className="hero-price" id="heroPrice">—</div>
              <div className="hero-sub"><span id="heroChg">—</span><span id="heroUpdated"></span></div>
            </div>
          </div>
          <div className="hero-stats">
            <div className="hstat"><div className="hl">24h High</div><div className="hv" id="hsHigh">—</div></div>
            <div className="hstat"><div className="hl">24h Low</div><div className="hv" id="hsLow">—</div></div>
            <div className="hstat"><div className="hl">24h Volume (USDT)</div><div className="hv" id="hsVol">—</div></div>
            <div className="hstat"><div className="hl">24h Trades</div><div className="hv" id="hsTrades">—</div></div>
            <div className="hstat"><div className="hl">Mark Price</div><div className="hv" id="hsMark">—</div></div>
          </div>
        </div>
      
        <div className="metric-grid">
          <div className="metric"><div className="ml"><span>Funding Rate</span><span className="badge b-purple">PERP</span></div><div className="mv" id="mFR">—</div><div className="ms" id="mFRNext">—</div></div>
          <div className="metric"><div className="ml"><span>Open Interest</span><span className="badge b-cyan">LIVE</span></div><div className="mv" id="mOI">—</div><div className="ms" id="mOISub">—</div></div>
          <div className="metric"><div className="ml"><span>RSI (14)</span><span className="badge b-gray" id="mRSIZone">—</span></div><div className="mv" id="mRSI">—</div><div className="ms">15m closes · Wilder</div></div>
          <div className="metric"><div className="ml"><span>MACD Signal</span><span className="badge b-gray" id="mMACDZone">—</span></div><div className="mv" id="mMACD">—</div><div className="ms" id="mMACDSub">12/26/9 histogram</div></div>
          <div className="metric"><div className="ml"><span>AI Composite</span><span className="badge b-gray" id="mAIZone">—</span></div><div className="mv" id="mAIScore">—</div><div className="score-track"><div className="score-marker" id="mAIMarker" style={{ 'left': 'calc(50% - 2px)' }}></div></div></div>
          <div className="metric"><div className="ml"><span>Volatility (24H est)</span><span className="badge b-amber">RISK</span></div><div className="mv" id="mVol">—</div><div className="ms">realized · 96×15m</div></div>
          <div className="metric"><div className="ml"><span>EMA (20)</span><span className="badge b-gray" id="mEMAZone">—</span></div><div className="mv" id="mEMA">—</div><div className="ms" id="mEMASub">—</div></div>
          <div className="metric"><div className="ml"><span>Bollinger %B</span><span className="badge b-gray" id="mBBZone">—</span></div><div className="mv" id="mBB">—</div><div className="ms" id="mBBSub">20, 2σ band position</div></div>
          <div className="metric"><div className="ml"><span>Volume Trend</span><span className="badge b-gray" id="mVTZone">—</span></div><div className="mv" id="mVT">—</div><div className="ms">last 10 vs prior 10 bars</div></div>
        </div>
      
        <DashHead zone="chart" name="Price Action" sub="Chart, drawing tools and the order-book side panel" />
        <DivergenceBanner />
        <Suspense fallback={null}><MLPredictionPanel /></Suspense>
        <Suspense fallback={null}><RLPolicyPanel /></Suspense>
        <ConfluencePanel />
        <OBImbalanceGauge />
        <div className="chart-host" id="chartHostRadar">
        <div className="card" id="radarChartCard">
          <div className="sec-head">
            <div className="sec-title" id="chartTitle">Price Action · 15m Candles</div>
            <div className="chart-toolbar">
              <TimeframePicker />
              <CoinPicker />
              {/* Filled and kept in sync by the engine; the picker above is its face. */}
              <select id="symSelect" hidden aria-hidden="true" tabIndex={-1}></select>
              <span className="badge b-cyan" id="wsKlineState">WS SYNCING</span>
              <LayoutPicker />
              <button className="chart-tool-btn" id="fsBtn" title="Full screen [F]" aria-label="Full screen">⛶</button>
            </div>
          </div>
      
          <ReplayBar />
          <div className="chart-stage">
            <div className="chart-layout" id="chartLayout">
              <div className="chart-wrap" id="chartWrap">
                <div className="legend" id="legendOHLC">Loading chart…</div>
                <div id="chart"></div>
                <span className="chart-draw-hint" id="drawHint"></span>
                <Guard name="Whale legend"><WhaleLegend /></Guard>
              </div>
            </div>
            <Guard name="Chart side panel">
              <ChartSidePanel
                tools={
                  <>
                    <ChartStylePicker />
                    <DrawToolPicker />
                    <IndicatorPicker />
                    <OverlayTogglePicker />
                    <ReplayButton />
                  </>
                }
              />
            </Guard>
          </div>
        </div>
        </div>
      
        <DashHead zone="analytics" name="Intelligence" sub="Sentiment, forecast and large-order flow" />
        <div className="desktop-grid">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Fear &amp; Greed Index</div><span className="badge b-pink">SENTIMENT</span></div>
            <div className="fng-wrap">
              <canvas id="gauge" width="130" height="130" style={{ 'width': '130px', 'height': '130px' }}></canvas>
              <div className="fng-meta">
                <div className="fng-big" id="fngVal">—</div>
                <div className="fng-class" id="fngClass">loading…</div>
                <div className="fng-note" id="fngNote">Aggregated crypto market sentiment from alternative.me</div>
              </div>
            </div>
          </div>
      
          <div className="card full">
            <div className="sec-head"><div className="sec-title">ML Price Forecast</div><span className="badge b-cyan">LINREG · 20P WINDOW</span></div>
            <div className="fc-bias">
              <div><div className="fb-l">Direction Bias</div><div className="fb-v" id="fcBias">—</div></div>
              <div style={{ 'textAlign': 'right' }}><div className="fb-l">Model Confidence (24H)</div><div className="fb-v" id="fcConf">—</div></div>
            </div>
            <div className="table-scroll">
            <table className="fc-table">
              <thead><tr><th>Horizon</th><th>Target</th><th>Δ%</th><th>Range (σ band)</th><th>Confidence</th></tr></thead>
              <tbody id="fcRows"></tbody>
            </table>
            </div>
            <div className="fc-note">Ordinary least squares regression on the last 20 × 15m closes, projected forward with damping. σ bands = realized per-bar volatility scaled by √horizon. Statistical estimate — not financial advice.</div>
          </div>
      
          <div className="card full">
            <div className="sec-head"><div className="sec-title">Whale Order Tracker</div><span className="badge b-amber" id="whaleCount">≥ $50,000</span></div>
            <div className="whale-list" id="whaleList"><div className="fc-note">Scanning tape for block trades…</div></div>
          </div>
        </div>

        <DashHead zone="flow" name="Market Flow" sub="Where price differs across venues, and who is being liquidated" />
        <div className="desktop-grid grid-2">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Cross-Exchange Radar</div><span className="badge b-cyan" id="advXexBadge">—</span></div>
            <Guard name="Cross-exchange radar"><Suspense fallback={null}><CrossExchangeTable /></Suspense></Guard>
          </div>

          <div className="card">
            <div className="sec-head"><div className="sec-title">Live Liquidations</div><span className="badge b-gray" id="advLiqBadge">ws closed</span></div>
            <div className="fc-note" id="advLiqTotals" style={{ 'margin': '0 0 8px' }}></div>
            <div className="table-scroll">
              <table className="fc-table">
                <thead><tr><th>Symbol</th><th>Type</th><th>Price</th><th>Notional</th><th>Time</th></tr></thead>
                <tbody id="advLiqBody"><tr><td colSpan={5} className="muted">Listening for forced orders…</td></tr></tbody>
              </table>
            </div>
            <div className="fc-note">All-market Binance USD-M forceOrder stream. Long liquidation = a long was forced out (sell side); notional is price × quantity.</div>
          </div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-multichart">
        <div className="chart-host" id="chartHostCharts"></div>
        <div className="card">
          <div className="sec-head"><div className="sec-title">Multi-Chart Workspace</div><span className="badge b-cyan">LIVE WS</span></div>
          <div className="multi-chart-grid" id="mcGrid"></div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-signals">
        <div className="sig-mode-tabs">
          <div className="sig-mode-tab active" data-sigmode="auto" onClick={() => { w.switchSigMode('auto') }}>Auto Scanner</div>
          <div className="sig-mode-tab" data-sigmode="search" onClick={() => { w.switchSigMode('search') }}>Coin Analysis</div>
        </div>
      
        <div id="sigAutoView">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Live Signal Scanner</div><span className="badge b-green" id="sigCount">SCANNING</span></div>
            <div className="sig-filters" id="sigFilters"></div>
            <div className="signal-grid" id="signalGrid"></div>
            <div className="disclaimer" style={{ 'marginTop': '14px' }}>Signals are generated from multi-indicator confluence (RSI, MACD, EMA, BB, volume, divergence). This is algorithmic analysis — not financial advice. Always do your own research.</div>
          </div>
        </div>
      
        <div id="sigSearchView" style={{ 'display': 'none' }}>
          <div className="sig-search-wrap" style={{ 'position': 'relative' }}>
            <span className="sig-search-icon">SEARCH</span>
            <input className="sig-search-box" id="sigSearchBox" type="text" placeholder="Search any coin... e.g. BTC, ETH, SOL, PEPE" onInput={(e) => { w.onSigSearch(e.currentTarget.value) }} onKeyDown={(e) => { if(e.key==='Enter')w.analyzeSigCoin(e.currentTarget.value) }} />
          </div>
          <div id="sigAnalysisResult"></div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-market">
        <div className="mo-strip">
          <div className="metric"><div className="ml"><span>Tracked Volume</span></div><div className="mv" id="moVol">—</div><div className="ms">sum of {HOT_LIST.length} majors (24h)</div></div>
          <div className="metric"><div className="ml"><span>Advancers</span></div><div className="mv" style={{ 'color': 'var(--green)' }} id="moAdv">—</div><div className="ms">of tracked set</div></div>
          <div className="metric"><div className="ml"><span>Decliners</span></div><div className="mv" style={{ 'color': 'var(--red)' }} id="moDec">—</div><div className="ms">of tracked set</div></div>
          <div className="metric"><div className="ml"><span>Fear &amp; Greed</span></div><div className="mv" id="moFG">—</div><div className="ms" id="moFGc">market sentiment</div></div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Top Coins</div><span className="badge b-cyan" id="topCoinsUpd">LIVE · BINANCE</span></div>
          <div className="table-scroll">
            <table className="coins-table cmc-table">
              <thead><tr><th className="cmc-rank">#</th><th>Coin</th><th>Price</th><th>1h %</th><th>24h %</th><th>Market Cap</th><th>Circulating Supply</th><th>Volume (24h)</th></tr></thead>
              <tbody id="coinsBody"></tbody>
            </table>
          </div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Perpetual Futures</div><span className="badge b-purple">USDT-M · BINANCE</span></div>
          <div className="table-scroll">
            <table className="coins-table cmc-table">
              <thead><tr><th className="cmc-rank">#</th><th>Contract</th><th>Mark Price</th><th>24h %</th><th>Funding (8h)</th><th>Open Interest</th><th>Volume (24h)</th></tr></thead>
              <tbody id="futuresBody"></tbody>
            </table>
          </div>
          <div className="disclaimer">Funding is charged/paid every 8h between longs and shorts — positive means longs pay shorts. Open interest is notional (contracts × mark price).</div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Celebrity &amp; Meme Coins</div><span className="badge b-pink">HIGH VOLATILITY</span></div>
          <div className="celeb-grid" id="celebGrid"></div>
          <div className="disclaimer">Meme assets routinely draw down 30–80%. Position sizes should reflect that these trade on narrative flow, not cash flows.</div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Meme Coin Universe</div><span className="badge b-pink" id="memeCount">SCANNING</span></div>
          <div className="table-scroll">
            <table className="coins-table">
              <thead><tr><th>Coin</th><th>Last Price</th><th>24h Change</th><th>24h Volume</th><th>Signal</th><th></th></tr></thead>
              <tbody id="memeBody"></tbody>
            </table>
          </div>
          <div className="disclaimer">Extended meme coverage — coins with high retail attention and narrative-driven price action. Click any row to load its chart.</div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-bubbles">
        <Suspense fallback={null}><BubblesCanvas /></Suspense>
      </section>
      
      <section className="tab-section" id="tab-analysis">
        <div className="card">
          <div className="sec-head"><div className="sec-title">Liquidation Heat Zones</div><span className="badge b-amber" id="liqSym">BTCUSDT</span></div>
          <div className="metric-grid" style={{ 'marginBottom': '13px' }}>
            <div className="metric"><div className="ml"><span>Open Interest (notional)</span></div><div className="mv" id="liqOI">—</div><div className="ms">USD · perpetual futures</div></div>
            <div className="metric"><div className="ml"><span>Mark Price</span></div><div className="mv" id="liqMark">—</div><div className="ms" id="liqMarkSrc">fapi premium index</div></div>
            <div className="metric"><div className="ml"><span>ATR (14×15m)</span></div><div className="mv" id="liqATR">—</div><div className="ms">average true range</div></div>
            <div className="metric"><div className="ml"><span>Support Distance</span></div><div className="mv" style={{ 'fontSize': '15px' }} id="liqLev">—</div><div className="ms">distance to major support</div></div>
          </div>
          <div className="liq-zones">
            <div className="liq-zone">
              <div className="liq-zh"><span className="badge b-red">SHORT LIQUIDATION CLUSTER</span><span className="fc-note" style={{ 'margin': '0' }}>above swing high</span></div>
              <div className="liq-range" id="liqShortRange">—</div>
              <div className="liq-bar"><i id="liqShortBar" style={{ 'width': '100%', 'background': 'linear-gradient(90deg,rgba(255,23,68,.15),var(--red))' }}></i></div>
              <div className="liq-est" id="liqShortEst">estimated magnet: —</div>
            </div>
            <div className="liq-zone">
              <div className="liq-zh"><span className="badge b-green">LONG LIQUIDATION CLUSTER</span><span className="fc-note" style={{ 'margin': '0' }}>below swing low</span></div>
              <div className="liq-range" id="liqLongRange">—</div>
              <div className="liq-bar"><i id="liqLongBar" style={{ 'width': '100%', 'background': 'linear-gradient(90deg,var(--green),rgba(0,230,118,.15))' }}></i></div>
              <div className="liq-est" id="liqLongEst">estimated magnet: —</div>
            </div>
          </div>
          <div className="disclaimer">Zones are heuristic estimates derived from swing structure + ATR offsets applied to open interest — Binance does not expose public liquidation heatmaps on REST. Treat magnitudes as directional intuition only.</div>
        </div>
      
        <Guard name="Liquidation heatmap"><Suspense fallback={null}><LiqHeatmap /></Suspense></Guard>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Volume Profile</div><span className="badge b-cyan" id="vpSym">BTCUSDT · 96 BARS</span></div>
          <div id="vpList"></div>
          <div className="fc-note">Distribution of traded volume across price bins over the last 96 × 15m candles. ★ POC = Point of Control (highest-volume node) — historically acts as a magnet price.</div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-neuralnet">
        <DashHead zone="analytics" name="Neural network" sub="Live weights and activations from whichever model you've trained" />
        <Suspense fallback={null}><NeuralNetPage /></Suspense>
      </section>
      
      <section className="tab-section" id="tab-news">
        {/* 1 — breaking, 2 — economic calendar, 3 — news */}
        <div className="breaking-box" id="breakingBox" style={{ 'display': 'none' }}>
          <div className="sec-head" style={{ 'marginBottom': '6px' }}><div className="sec-title" style={{ 'color': 'var(--red)' }}>Breaking</div><span className="bb-live">LIVE WIRE</span></div>
          <div id="breakingList"></div>
        </div>

        <Guard name="Economic calendar"><Suspense fallback={null}><EconomicCalendar /></Suspense></Guard>

        <div className="news-grid">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Latest Crypto News</div><span className="badge b-cyan" id="newsCount">—</span></div>
            <div className="news-toolbar">
              <input type="text" id="newsSearch" className="news-search" placeholder="🔍 Search news…" autoComplete="off" />
              <button className="news-src-clear" id="newsSrcClear" style={{ 'display': 'none' }} title="Clear source filter">✕ <span id="newsSrcName"></span></button>
            </div>
            <div className="news-sent-row" id="newsSentRow" style={{ 'display': 'none' }}>
              <div className="ns-gauge-wrap"><div className="ns-gauge" id="newsSentGauge"><div className="ns-gauge-fill" id="newsSentFill"></div></div><span className="ns-gauge-lbl" id="newsSentLbl">Neutral</span></div>
              <span className="ns-count" id="newsSentCount"></span>
            </div>
            <div className="news-src-strip" id="newsSrcStrip"></div>
            <div className="news-src-strip" id="newsCoinStrip"></div>
            <div id="newsList"><div className="fc-note">Loading live feed…</div></div>
            <button className="news-more" id="newsMore" style={{ 'display': 'none' }}>Load more stories</button>
          </div>
          <div className="card">
            <div className="sec-head">
              <div className="sec-title">Trending Coins</div>
              <span className="badge b-purple">IN THE NEWS</span>
            </div>
            <div className="tc-note">Ranked by how many stories in the feed name each coin — tap one to filter.</div>
            <div id="trendingList"><div className="fc-note">Loading trends…</div></div>
          </div>
        </div>
      </section>

      <section className="tab-section" id="tab-settings">
        <DashHead zone="analytics" name="Settings" sub="Every data source this app uses, what it is for, and whether it is answering" />
        <Guard name="Settings"><Suspense fallback={null}><SettingsPage /></Suspense></Guard>
      </section>

      <section className="tab-section" id="tab-pro">
        <div className="pro-frame">
          <iframe ref={proRef} id="proFrame" title="Pro Terminal" aria-label="Embedded Pro Terminal (order book, tape, liquidations, cross-exchange, structure, futures, alerts, news)"></iframe>
        </div>
      </section>

      </main>
      <Footer />
      </div>
      
      <div className="toast" id="toast"></div>

      <Guard name="Radar AI"><Suspense fallback={null}><AiAssistant /></Suspense></Guard>
      
      <div className="modal-overlay" id="alModal" role="dialog" aria-modal="true" aria-label="Price alerts" onClick={(e) => { if(e.target=== e.currentTarget)w.closeModal('alModal') }}>
        <div className="modal-box" style={{ 'maxWidth': '480px' }}>
          <div className="modal-head">
            <div>Price Alerts</div>
            <button className="modal-x" onClick={() => { w.closeModal('alModal') }}>X</button>
          </div>
          <div className="modal-body">
            <div className="pf-field" style={{ 'display': 'flex', 'gap': '8px' }}>
              <input id="alSym" className="pf-input" placeholder="Symbol (BTCUSDT)" style={{ 'flex': '1' }} autoComplete="off" />
              <select id="alDir" className="pf-input" style={{ 'flex': '0 0 92px' }}>
                <option value="above">Above</option>
                <option value="below">Below</option>
              </select>
              <input id="alPrice" className="pf-input" type="number" step="any" min="0" placeholder="Price" style={{ 'flex': '1' }} />
            </div>
            <button className="tb-btn" style={{ 'width': '100%', 'marginTop': '2px' }} onClick={(e) => { w.addAlert(w.$('alSym').value,w.$('alDir').value,w.$('alPrice').value) }}>Set Alert</button>
            <div className="al-perm" id="alPerm">Desktop notifications: <b id="alPermState">off</b> — <button className="al-enable-btn" onClick={() => { w.enableAlerts() }}>Enable</button></div>
            <div style={{ 'marginTop': '8px', 'fontSize': '11px', 'color': 'var(--dim)' }}>Alerts are checked live and fire desktop notifications + toasts.</div>
            <div className="al-list" id="alList"></div>
          </div>
        </div>
      </div>
      
      <div className="modal-overlay" id="thModal" role="dialog" aria-modal="true" aria-label="Color themes" onClick={(e) => { if(e.target=== e.currentTarget)w.closeModal('thModal') }}>
        <div className="modal-box" style={{ 'maxWidth': '560px' }}>
          <div className="modal-head">
            <div>Color Themes</div>
            <button className="modal-x" onClick={() => { w.closeModal('thModal') }}>X</button>
          </div>
          <div className="modal-body">
            <div style={{ 'fontSize': '12px', 'color': 'var(--muted)', 'marginBottom': '4px' }}>Pick a color combo — the whole interface (with dark &amp; light) follows. Your choice is saved automatically.</div>
            <div className="pal-grid" id="palGrid"></div>
          </div>
        </div>
      </div>
      
      
      

    </>
  )
}
