// Liquidity Radar — React shell DOM (Phase 1 migration).
// Mechanical 1:1 port of the original index.html body. Ids/classes/palette
// are preserved verbatim so the engine (src/engine) can drive the tree
// exactly as in the vanilla app. Regenerated by scripts/html2jsx.cjs from
// the original index.html — do not hand-edit; App.tsx consumes <Shell/>.
const w = window as any

export function Shell() {
  return (
    <>
      <header className="top">
        <div className="top-inner">
          <div className="logo"><span className="dish">📡</span><span className="logo-text"><b>LIQUIDITY</b>&nbsp;RADAR</span></div>
          <div style={{ 'display': 'flex', 'alignItems': 'center', 'gap': '8px' }}>
            <button className="theme-btn" id="alertBtn" title="Price alerts (desktop notifications)" style={{ 'fontSize': '13px', 'fontWeight': '800', 'fontFamily': 'var(--mono)' }}>AL</button>
            <button className="theme-btn" id="paletteBtn" title="Color themes / palettes" style={{ 'fontSize': '15px', 'fontWeight': '800' }}>🎨</button>
            <button className="theme-btn" id="themeBtn" title="Toggle dark/light mode" style={{ 'fontSize': '12px', 'fontWeight': '800', 'fontFamily': 'var(--mono)' }}>D</button>
            <div className="status-pill" id="statusPill"><span className="dot"></span><span id="statusTxt">CONNECTING…</span></div>
          </div>
        </div>
        <div className="tickerbar"><div className="ticker-track" id="tickerTrack"></div></div>
        <nav className="tabs">
          <button className="tab-btn active" data-tab="radar" aria-label="Radar tab" aria-selected="true">[R] Radar</button>
          <button className="tab-btn" data-tab="multichart" aria-label="Charts tab" aria-selected="false">[C] Charts</button>
          <button className="tab-btn" data-tab="signals" aria-label="Signals tab" aria-selected="false">[S] Signals</button>
          <button className="tab-btn" data-tab="market" aria-label="Market tab" aria-selected="false">[M] Market</button>
          <button className="tab-btn" data-tab="bubbles" aria-label="Bubbles tab" aria-selected="false">[B] Bubbles</button>
          <button className="tab-btn" data-tab="analysis" aria-label="Analysis tab" aria-selected="false">[A] Analysis</button>
          <button className="tab-btn" data-tab="news" aria-label="News tab" aria-selected="false">[N] News</button>
          <button className="tab-btn" data-tab="portfolio" aria-label="Portfolio tab" aria-selected="false">[$] Portfolio</button>
          <button className="tab-btn" data-tab="chat" aria-label="AI Chat tab" aria-selected="false">[T] AI Chat</button>
        </nav>
      </header>
      
      <div className="search-wrap">
        <span className="search-icon">🔍</span>
        <input className="search-box" id="coinSearch" type="text" placeholder="Search any coin... (e.g. PEPE, SOL, DOGE, PEPEPE, TRUMP)" autoComplete="off" maxLength={50} />
        <div className="search-results" id="searchResults"></div>
      </div>
      
      <div className="container">
      <main>
      
      <section className="tab-section active" id="tab-radar">
        <div className="card hero-card">
          <div className="hero-main">
            <div className="hero-id">
              <div className="hero-icon" id="heroIcon">₿</div>
              <div>
                <div className="hero-name" id="heroName">Bitcoin</div>
                <div className="hero-pair" id="heroPair">BTCUSDT · BINANCE SPOT</div>
              </div>
            </div>
            <div className="hero-price-block">
              <div className="hero-price" id="heroPrice">—</div>
              <div className="hero-sub"><span id="heroChg">—</span><span id="heroUpdated"></span></div>
            </div>
          </div>
          <div className="hero-stats">
            <div className="hstat"><div className="hl">24h High</div><div className="hv" id="hsHigh">—</div></div>
            <div className="hstat"><div className="hl">24h Low</div><div className="hv" id="hsLow">—</div></div>
            <div className="hstat"><div className="hl">24h Volume (USDT)</div><div className="hv" id="hsVol">—</div></div>
            <div className="hstat"><div className="hl">24h Trades</div><div className="hv" id="hsTrades">—</div></div>
            <div className="hstat"><div className="hl">Mark Price</div><div className="hv" id="hsMark">—</div></div>
          </div>
        </div>
      
        <div className="metric-grid">
          <div className="metric"><div className="ml"><span>Funding Rate</span><span className="badge b-purple">PERP</span></div><div className="mv" id="mFR">—</div><div className="ms" id="mFRNext">—</div></div>
          <div className="metric"><div className="ml"><span>Open Interest</span><span className="badge b-cyan">LIVE</span></div><div className="mv" id="mOI">—</div><div className="ms" id="mOISub">—</div></div>
          <div className="metric"><div className="ml"><span>RSI (14)</span><span className="badge b-gray" id="mRSIZone">—</span></div><div className="mv" id="mRSI">—</div><div className="ms">15m closes · Wilder</div></div>
          <div className="metric"><div className="ml"><span>MACD Signal</span><span className="badge b-gray" id="mMACDZone">—</span></div><div className="mv" id="mMACD">—</div><div className="ms">12/26/9 histogram</div></div>
          <div className="metric"><div className="ml"><span>AI Composite</span><span className="badge b-gray" id="mAIZone">—</span></div><div className="mv" id="mAIScore">—</div><div className="score-track"><div className="score-marker" id="mAIMarker" style={{ 'left': 'calc(50% - 2px)' }}></div></div></div>
          <div className="metric"><div className="ml"><span>Volatility (24H est)</span><span className="badge b-amber">RISK</span></div><div className="mv" id="mVol">—</div><div className="ms">realized · 96×15m</div></div>
          <div className="metric"><div className="ml"><span>EMA (20)</span><span className="badge b-gray" id="mEMAZone">—</span></div><div className="mv" id="mEMA">—</div><div className="ms" id="mEMASub">—</div></div>
          <div className="metric"><div className="ml"><span>Bollinger %B</span><span className="badge b-gray" id="mBBZone">—</span></div><div className="mv" id="mBB">—</div><div className="ms">20, 2σ band position</div></div>
        </div>
      
        <div className="card" id="radarChartCard">
          <div className="sec-head">
            <div className="sec-title" id="chartTitle">Price Action · 15m Candles</div>
            <div className="chart-toolbar">
              <div className="tf-switch" id="tfSwitch">
                <button className="tf-btn" data-tf="1m">1m</button>
                <button className="tf-btn" data-tf="5m">5m</button>
                <button className="tf-btn active" data-tf="15m">15m</button>
                <button className="tf-btn" data-tf="1h">1h</button>
                <button className="tf-btn" data-tf="4h">4h</button>
                <button className="tf-btn" data-tf="1d">1d</button>
              </div>
              <select id="symSelect"></select>
              <span className="badge b-cyan" id="wsKlineState">WS SYNCING</span>
              <button className="chart-tool-btn" id="fsBtn" title="Full screen [F]" aria-label="Full screen">⛶</button>
            </div>
          </div>
      
          <div className="chart-btnrow" id="chartBtnRow">
            <div className="tv-group" data-group="ind">
              <span className="tv-lbl">Indicators</span>
              <button className="tv-chip" data-ind="ema" data-on="1">EMA</button>
              <button className="tv-chip" data-ind="sma" data-on="1">SMA</button>
              <button className="tv-chip" data-ind="boll" data-on="1">Boll</button>
              <button className="tv-chip" data-ind="vwap" data-on="0">VWAP</button>
              <input className="tv-num" id="indPeriod" type="number" min="2" max="200" value="20" title="Indicator period" />
            </div>
            <div className="tv-group" data-group="pane">
              <span className="tv-lbl">Panes</span>
              <button className="tv-chip" data-pane="vol" data-on="1">Volume</button>
              <button className="tv-chip" data-pane="rsi" data-on="0">RSI</button>
              <button className="tv-chip" data-pane="macd" data-on="0">MACD</button>
            </div>
            <div className="tv-group" data-group="drw">
              <span className="tv-lbl">Draw</span>
              <button className="tv-chip" data-drw="hline" data-on="0">↔ Line</button>
              <button className="tv-chip" data-drw="trend" data-on="0">↗ Trend</button>
              <button className="tv-chip" data-drw="ray" data-on="0">⌁ Ray</button>
            </div>
            <div className="tv-group">
              <span className="tv-lbl">Style</span>
              <select className="tv-select" id="chartStyle">
                <option value="candle">Candles</option>
                <option value="area">Area</option>
                <option value="line">Line</option>
                <option value="hollow">Hollow</option>
              </select>
            </div>
            <span className="tv-hint" id="drawHint">Select a drawing tool, then click two points on the chart</span>
          </div>
      
          <div className="chart-wrap" id="chartWrap">
            <div className="legend" id="legendOHLC">Loading chart…</div>
            <div id="chart"></div>
          </div>
        </div>
      
        <div className="desktop-grid">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Technical Indicators</div><span className="badge b-purple">AI FUSED</span></div>
            <div className="ind-row"><div><div className="ind-name">RSI (14)</div><div className="ind-sub">overbought &gt;70 / oversold &lt;30</div></div><div style={{ 'textAlign': 'right' }}><div className="ind-val" id="indRSI">—</div><span className="badge b-gray" id="indRSIb">—</span></div></div>
            <div className="ind-row"><div><div className="ind-name">MACD (12,26,9)</div><div className="ind-sub">bullish when histogram &gt; 0</div></div><div style={{ 'textAlign': 'right' }}><div className="ind-val" id="indMACD">—</div><span className="badge b-gray" id="indMACDb">—</span></div></div>
            <div className="ind-row"><div><div className="ind-name">EMA (20)</div><div className="ind-sub">trend filter baseline</div></div><div style={{ 'textAlign': 'right' }}><div className="ind-val" id="indEMA">—</div><span className="badge b-gray" id="indEMAb">—</span></div></div>
            <div className="ind-row"><div><div className="ind-name">Bollinger Bands (20,2)</div><div className="ind-sub" id="indBBs">%B band position</div></div><div style={{ 'textAlign': 'right' }}><div className="ind-val" id="indBB">—</div><span className="badge b-gray" id="indBBb">—</span></div></div>
            <div className="ind-row"><div><div className="ind-name">Volume Trend</div><div className="ind-sub">last 10 vs prior 10 bars</div></div><div style={{ 'textAlign': 'right' }}><div className="ind-val" id="indVT">—</div><span className="badge b-gray" id="indVTb">—</span></div></div>
            <div className="score-bar-wrap">
              <div className="ob-head" style={{ 'paddingBottom': '4px' }}><span>AI COMPOSITE SCORE</span><span id="indScoreLbl" style={{ 'color': 'var(--muted)' }}>—</span></div>
              <div className="score-track"><div className="score-marker" id="indScoreMarker" style={{ 'left': 'calc(50% - 2px)' }}></div></div>
              <div style={{ 'display': 'flex', 'justifyContent': 'space-between', 'fontFamily': 'var(--mono)', 'fontSize': '9.5px', 'color': 'var(--dim)', 'marginTop': '4px' }}><span>-100 SELL</span><span>0</span><span>+100 BUY</span></div>
            </div>
          </div>
      
          <div className="card">
            <div className="sec-head"><div className="sec-title">Order Book</div><span className="badge b-green">DEPTH ±15</span></div>
            <div className="ob-head"><span>Price</span><span>Size</span></div>
            <div id="obAsks"></div>
            <div className="ob-spread"><span id="obSpreadV">spread —</span><span id="obMid">mid —</span></div>
            <div id="obBids"></div>
          </div>
      
          <div className="card">
            <div className="sec-head"><div className="sec-title">Liquidity Heatmap</div><span className="badge b-red" id="hmSym">—</span></div>
            <div id="hmAsks"></div>
            <div className="hm-sep" id="hmMid">—— SPREAD ——</div>
            <div id="hmBids"></div>
          </div>
      
          <div className="card">
            <div className="sec-head"><div className="sec-title">Fear &amp; Greed Index</div><span className="badge b-pink">SENTIMENT</span></div>
            <div className="fng-wrap">
              <canvas id="gauge" width="130" height="130" style={{ 'width': '130px', 'height': '130px' }}></canvas>
              <div className="fng-meta">
                <div className="fng-big" id="fngVal">—</div>
                <div className="fng-class" id="fngClass">loading…</div>
                <div className="fng-note" id="fngNote">Aggregated crypto market sentiment from alternative.me</div>
              </div>
            </div>
          </div>
      
          <div className="card full">
            <div className="sec-head"><div className="sec-title">ML Price Forecast</div><span className="badge b-cyan">LINREG · 20P WINDOW</span></div>
            <div className="fc-bias">
              <div><div className="fb-l">Direction Bias</div><div className="fb-v" id="fcBias">—</div></div>
              <div style={{ 'textAlign': 'right' }}><div className="fb-l">Model Confidence (24H)</div><div className="fb-v" id="fcConf">—</div></div>
            </div>
            <div className="table-scroll">
            <table className="fc-table">
              <thead><tr><th>Horizon</th><th>Target</th><th>Δ%</th><th>Range (σ band)</th><th>Confidence</th></tr></thead>
              <tbody id="fcRows"></tbody>
            </table>
            </div>
            <div className="fc-note">Ordinary least squares regression on the last 20 × 15m closes, projected forward with damping. σ bands = realized per-bar volatility scaled by √horizon. Statistical estimate — not financial advice.</div>
          </div>
      
          <div className="card full">
            <div className="sec-head"><div className="sec-title">Whale Order Tracker</div><span className="badge b-amber" id="whaleCount">≥ $50,000</span></div>
            <div className="whale-list" id="whaleList"><div className="fc-note">Scanning tape for block trades…</div></div>
          </div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-portfolio">
        <div className="card">
          <div className="sec-head">
            <div className="sec-title">Portfolio Tracker</div>
            <div className="chart-toolbar">
              <button className="tb-btn" id="pfAddBtn">+ Add Position</button>
              <span className="badge b-cyan" id="pfStatus">LIVE</span>
            </div>
          </div>
          <div className="pf-summary">
            <div className="pf-stat"><div className="fb-l">Total Value</div><div className="fb-v" id="pfTotal">—</div></div>
            <div className="pf-stat"><div className="fb-l">Unrealized PnL</div><div className="fb-v" id="pfPnl">—</div></div>
            <div className="pf-stat"><div className="fb-l">Day Change (24h)</div><div className="fb-v" id="pfDay">—</div></div>
            <div className="pf-stat"><div className="fb-l">Positions</div><div className="fb-v" id="pfCount">0</div></div>
          </div>
          <div className="table-scroll">
            <table className="fc-table">
              <thead><tr><th>Coin</th><th>Qty</th><th>Avg Cost</th><th>Price</th><th>24h</th><th>Value</th><th>PnL</th><th style={{ 'width': '60px' }}></th></tr></thead>
              <tbody id="pfRows"></tbody>
            </table>
          </div>
          <div className="fc-note" id="pfEmpty">No positions yet. Click <b>+ Add Position</b> to start tracking your holdings with live prices and PnL.</div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-multichart">
        <div className="card">
          <div className="sec-head"><div className="sec-title">Multi-Chart Workspace</div><span className="badge b-cyan">LIVE WS</span></div>
          <div className="multi-chart-grid" id="mcGrid"></div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-signals">
        <div className="sig-mode-tabs">
          <div className="sig-mode-tab active" data-sigmode="auto" onClick={() => { w.switchSigMode('auto') }}>Auto Scanner</div>
          <div className="sig-mode-tab" data-sigmode="search" onClick={() => { w.switchSigMode('search') }}>Coin Analysis</div>
        </div>
      
        <div id="sigAutoView">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Live Signal Scanner</div><span className="badge b-green" id="sigCount">SCANNING</span></div>
            <div className="signal-grid" id="signalGrid"></div>
            <div className="disclaimer" style={{ 'marginTop': '14px' }}>Signals are generated from multi-indicator confluence (RSI, MACD, EMA, BB, volume, divergence). This is algorithmic analysis — not financial advice. Always do your own research.</div>
          </div>
        </div>
      
        <div id="sigSearchView" style={{ 'display': 'none' }}>
          <div className="sig-search-wrap" style={{ 'position': 'relative' }}>
            <span className="sig-search-icon">SEARCH</span>
            <input className="sig-search-box" id="sigSearchBox" type="text" placeholder="Search any coin... e.g. BTC, ETH, SOL, PEPE" onInput={(e) => { w.onSigSearch(e.currentTarget.value) }} onKeyDown={(e) => { if(e.key==='Enter')w.analyzeSigCoin(e.currentTarget.value) }} />
          </div>
          <div id="sigAnalysisResult"></div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-market">
        <div className="mo-strip">
          <div className="metric"><div className="ml"><span>Tracked Volume</span></div><div className="mv" id="moVol">—</div><div className="ms">sum of 16 majors (24h)</div></div>
          <div className="metric"><div className="ml"><span>Advancers</span></div><div className="mv" style={{ 'color': 'var(--green)' }} id="moAdv">—</div><div className="ms">of tracked set</div></div>
          <div className="metric"><div className="ml"><span>Decliners</span></div><div className="mv" style={{ 'color': 'var(--red)' }} id="moDec">—</div><div className="ms">of tracked set</div></div>
          <div className="metric"><div className="ml"><span>Fear &amp; Greed</span></div><div className="mv" id="moFG">—</div><div className="ms" id="moFGc">market sentiment</div></div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Top Coins</div><span className="badge b-cyan" id="topCoinsUpd">LIVE · BINANCE</span></div>
          <div className="table-scroll">
            <table className="coins-table">
              <thead><tr><th>Coin</th><th>Last Price</th><th>24h Change</th><th>24h Volume</th><th>Signal</th></tr></thead>
              <tbody id="coinsBody"></tbody>
            </table>
          </div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Celebrity &amp; Meme Coins</div><span className="badge b-pink">HIGH VOLATILITY</span></div>
          <div className="celeb-grid" id="celebGrid"></div>
          <div className="disclaimer">Meme assets routinely draw down 30–80%. Position sizes should reflect that these trade on narrative flow, not cash flows.</div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Meme Coin Universe</div><span className="badge b-pink" id="memeCount">SCANNING</span></div>
          <div className="table-scroll">
            <table className="coins-table">
              <thead><tr><th>Coin</th><th>Last Price</th><th>24h Change</th><th>24h Volume</th><th>Signal</th><th></th></tr></thead>
              <tbody id="memeBody"></tbody>
            </table>
          </div>
          <div className="disclaimer">Extended meme coverage — coins with high retail attention and narrative-driven price action. Click any row to load its chart.</div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-bubbles">
        <div className="card">
          <div className="sec-head"><div className="sec-title">Crypto Bubbles</div><span className="badge b-cyan" id="bubCount">—</span></div>
          <div className="bub-ctrl">
            <div className="bub-filter">
              <button className="bub-f on" data-f="all">All Coins</button>
              <button className="bub-f" data-f="major">Majors</button>
              <button className="bub-f" data-f="meme">Memes</button>
            </div>
            <div className="bub-legend">
              <span><i className="lg sog"></i>Gainers</span>
              <span><i className="lg sor"></i>Losers</span>
              <span className="bub-hint">Size = 24h traded volume · color = 24h change · click a bubble to open its chart</span>
            </div>
          </div>
          <div className="bub-wrap" id="bubWrap"><div className="bub-empty">Loading live prices…</div></div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-analysis">
        <div className="card">
          <div className="sec-head"><div className="sec-title">Liquidation Heat Zones</div><span className="badge b-amber" id="liqSym">BTCUSDT</span></div>
          <div className="metric-grid" style={{ 'marginBottom': '13px' }}>
            <div className="metric"><div className="ml"><span>Open Interest (notional)</span></div><div className="mv" id="liqOI">—</div><div className="ms">USD · perpetual futures</div></div>
            <div className="metric"><div className="ml"><span>Mark Price</span></div><div className="mv" id="liqMark">—</div><div className="ms">fapi premium index</div></div>
            <div className="metric"><div className="ml"><span>ATR (14×15m)</span></div><div className="mv" id="liqATR">—</div><div className="ms">average true range</div></div>
            <div className="metric"><div className="ml"><span>Support Distance</span></div><div className="mv" style={{ 'fontSize': '15px' }} id="liqLev">—</div><div className="ms">distance to major support</div></div>
          </div>
          <div className="liq-zone">
            <div className="liq-zh"><span className="badge b-red">SHORT LIQUIDATION CLUSTER</span><span className="fc-note" style={{ 'margin': '0' }}>above swing high</span></div>
            <div className="liq-range" id="liqShortRange">—</div>
            <div className="liq-bar"><i id="liqShortBar" style={{ 'width': '100%', 'background': 'linear-gradient(90deg,rgba(255,23,68,.15),var(--red))' }}></i></div>
            <div className="liq-est" id="liqShortEst">estimated magnet: —</div>
          </div>
          <div className="liq-zone">
            <div className="liq-zh"><span className="badge b-green">LONG LIQUIDATION CLUSTER</span><span className="fc-note" style={{ 'margin': '0' }}>below swing low</span></div>
            <div className="liq-range" id="liqLongRange">—</div>
            <div className="liq-bar"><i id="liqLongBar" style={{ 'width': '100%', 'background': 'linear-gradient(90deg,var(--green),rgba(0,230,118,.15))' }}></i></div>
            <div className="liq-est" id="liqLongEst">estimated magnet: —</div>
          </div>
          <div className="disclaimer">Zones are heuristic estimates derived from swing structure + ATR offsets applied to open interest — Binance does not expose public liquidation heatmaps on REST. Treat magnitudes as directional intuition only.</div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Live Liquidation Heat Map</div><span className="badge b-cyan" id="liqHmSym">BTCUSDT</span></div>
          <div className="hm-ctrl">
            <span className="hm-met" id="hmOI">OI —</span>
            <span className="hm-met" id="hmStress">Stress —</span>
            <span className="hm-met" id="hmBreadth">Breadth —</span>
            <span className="hm-hint" id="hmUpd">—</span>
          </div>
          <div className="hm-wrap">
            <canvas id="hmCanvas"></canvas>
          </div>
          <div className="hm-legend">
            <span><i className="lg sog"></i>Long-liquidations (below)</span>
            <span><i className="lg sor"></i>Short-liquidations (above)</span>
            <span className="hm-note">Heat = inferred cascade pressure from live OI, ATR &amp; market breadth · price % vs current mark · sweeps every few seconds</span>
          </div>
        </div>
      
        <div className="card">
          <div className="sec-head"><div className="sec-title">Volume Profile</div><span className="badge b-cyan" id="vpSym">BTCUSDT · 96 BARS</span></div>
          <div id="vpList"></div>
          <div className="fc-note">Distribution of traded volume across price bins over the last 96 × 15m candles. ★ POC = Point of Control (highest-volume node) — historically acts as a magnet price.</div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-news">
        <div className="breaking-box" id="breakingBox" style={{ 'display': 'none' }}>
          <div className="sec-head" style={{ 'marginBottom': '6px' }}><div className="sec-title" style={{ 'color': 'var(--red)' }}>Breaking</div><span className="bb-live">LIVE WIRE</span></div>
          <div id="breakingList"></div>
        </div>
      
        <div className="card fx-macro-card">
          <div className="fx-head">
            <div className="fx-title-wrap">
              <div className="fx-title-icon">🗓️</div>
              <div>
                <div className="fx-title">Forex Factory Economic Calendar</div>
                <div className="fx-sub">Weekly schedule · same layout &amp; fields as forexfactory.com · auto-refreshes</div>
              </div>
            </div>
            <div className="fx-impact-legend">
              <span className="fx-legend-lbl">FILTER</span>
              <span className="fx-im fx-im-hi" data-fx-filter="High" title="Filter: High impact only"><i></i>High</span>
              <span className="fx-im fx-im-md" data-fx-filter="Medium" title="Filter: Medium impact only"><i></i>Medium</span>
              <span className="fx-im fx-im-lo" data-fx-filter="Low" title="Filter: Low impact only"><i></i>Low</span>
              <span className="fx-im fx-im-all" data-fx-filter="All" title="Show all"><i></i>All</span>
              <span className="badge b-amber" id="fxCount">—</span>
            </div>
          </div>
          <div className="fx-scroll" id="forexScroll">
            <div className="fx-colhead">
              <span className="fx-c-time">Time</span>
              <span className="fx-c-cur">Cur.</span>
              <span className="fx-c-imp">Imp.</span>
              <span className="fx-c-ev">Event</span>
              <span className="fx-c-num">Actual</span>
              <span className="fx-c-num">Forecast</span>
              <span className="fx-c-num">Previous</span>
            </div>
            <div id="forexList"><div className="fc-note">Loading economic calendar…</div></div>
          </div>
        </div>
      
        <div className="news-grid">
          <div className="card">
            <div className="sec-head"><div className="sec-title">Latest Crypto News</div><span className="badge b-cyan" id="newsCount">—</span></div>
            <div className="news-toolbar">
              <input type="text" id="newsSearch" className="news-search" placeholder="🔍 Search news…" autoComplete="off" />
              <button className="news-src-clear" id="newsSrcClear" style={{ 'display': 'none' }} title="Clear source filter">✕ <span id="newsSrcName"></span></button>
            </div>
            <div className="news-sent-row" id="newsSentRow" style={{ 'display': 'none' }}>
              <div className="ns-gauge-wrap"><div className="ns-gauge" id="newsSentGauge"><div className="ns-gauge-fill" id="newsSentFill"></div></div><span className="ns-gauge-lbl" id="newsSentLbl">Neutral</span></div>
              <span className="ns-count" id="newsSentCount"></span>
            </div>
            <div className="news-src-strip" id="newsSrcStrip"></div>
            <div className="news-src-strip" id="newsCoinStrip"></div>
            <div id="newsList"><div className="fc-note">Loading live feed…</div></div>
            <button className="news-more" id="newsMore" style={{ 'display': 'none' }}>Load more stories</button>
          </div>
          <div>
            <div className="card">
              <div className="sec-head"><div className="sec-title">Trending Now</div><span className="badge b-purple">HEAT</span></div>
              <div id="trendingList"><div className="fc-note">Loading trends…</div></div>
            </div>
          </div>
        </div>
      </section>
      
      <section className="tab-section" id="tab-chat">
        <div className="card chat-card">
          <div className="chat-head">
            <div className="ai-avatar">🤖</div>
            <div>
              <div style={{ 'fontWeight': '800' }}>Radar AI Assistant</div>
              <div style={{ 'fontSize': '11px', 'color': 'var(--muted)' }}>Knows 29 coins live · indicators · whales · sentiment — ask anything</div>
            </div>
            <span className="badge b-green" style={{ 'marginLeft': 'auto' }}>ONLINE</span>
          </div>
          <div className="chat-log" id="chatLog"></div>
          <div className="chips" id="chatChips">
            <button className="chip" data-q="Analyze BTC">📈 Analyze BTC</button>
            <button className="chip" data-q="What is RSI?">🧠 What is RSI?</button>
            <button className="chip" data-q="Should I buy pepe?">Buy PEPE?</button>
            <button className="chip" data-q="Show meme coins">🐕 Meme coins</button>
            <button className="chip" data-q="Show signals">⚡ Show signals</button>
            <button className="chip" data-q="Fear and greed now">Fear &amp; Greed</button>
            <button className="chip" data-q="Best performer today">Top gainer today</button>
            <button className="chip" data-q="Whale activity?">Whale watch</button>
            <button className="chip" data-q="What patterns do you see?">🔍 Patterns</button>
            <button className="chip" data-q="What can you do">Help</button>
          </div>
          <form className="chat-input-row" id="chatForm">
            <input type="text" id="chatInput" placeholder="Ask about any coin, indicator, whale moves…" autoComplete="off" maxLength={300} />
            <button className="send-btn" type="submit" id="sendBtn">Send ➤</button>
          </form>
        </div>
      </section>
      
      </main>
      <footer>
        LIQUIDITY RADAR v5.0 &middot; Created by <b>Zain</b> &middot; microstructure terminal &middot; data: Binance Spot &amp; Futures WS/REST &middot; sentiment: alternative.me &middot; news: CoinDesk, Cointelegraph, CryptoSlate, Decrypt, The Block, CoinGape, BeInCrypto, Bitcoin Magazine (via RSS2JSON)<br />
        Everything on this page is informational tooling — not financial advice. Trade at your own risk.
      </footer>
      </div>
      
      <div className="toast" id="toast"></div>
      
      <div className="modal-overlay" id="pfModal" role="dialog" aria-modal="true" aria-label="Add position" onClick={(e) => { if(e.target=== e.currentTarget)w.closeModal('pfModal') }}>
        <div className="modal-box">
          <div className="modal-head">
            <div>Add Position</div>
            <button className="modal-x" onClick={() => { w.closeModal('pfModal') }}>X</button>
          </div>
          <div className="modal-body">
            <div className="pf-field"><label>Symbol (e.g. BTCUSDT)</label><input id="pfSym" className="pf-input" placeholder="BTCUSDT" autoComplete="off" /></div>
            <div className="pf-field"><label>Quantity</label><input id="pfQty" className="pf-input" type="number" step="any" min="0" placeholder="0.5" /></div>
            <div className="pf-field"><label>Average Cost (USD)</label><input id="pfCost" className="pf-input" type="number" step="any" min="0" placeholder="50000" /></div>
            <button className="tb-btn" style={{ 'width': '100%', 'marginTop': '6px' }} onClick={(e) => { w.addPosition(w.$('pfSym').value,w.$('pfQty').value,w.$('pfCost').value) }}>Save Position</button>
          </div>
        </div>
      </div>
      
      <div className="modal-overlay" id="alModal" role="dialog" aria-modal="true" aria-label="Price alerts" onClick={(e) => { if(e.target=== e.currentTarget)w.closeModal('alModal') }}>
        <div className="modal-box" style={{ 'maxWidth': '480px' }}>
          <div className="modal-head">
            <div>Price Alerts</div>
            <button className="modal-x" onClick={() => { w.closeModal('alModal') }}>X</button>
          </div>
          <div className="modal-body">
            <div className="pf-field" style={{ 'display': 'flex', 'gap': '8px' }}>
              <input id="alSym" className="pf-input" placeholder="Symbol (BTCUSDT)" style={{ 'flex': '1' }} autoComplete="off" />
              <select id="alDir" className="pf-input" style={{ 'flex': '0 0 92px' }}>
                <option value="above">Above</option>
                <option value="below">Below</option>
              </select>
              <input id="alPrice" className="pf-input" type="number" step="any" min="0" placeholder="Price" style={{ 'flex': '1' }} />
            </div>
            <button className="tb-btn" style={{ 'width': '100%', 'marginTop': '2px' }} onClick={(e) => { w.addAlert(w.$('alSym').value,w.$('alDir').value,w.$('alPrice').value) }}>Set Alert</button>
            <div className="al-perm" id="alPerm">Desktop notifications: <b id="alPermState">off</b> — <button className="al-enable-btn" onClick={() => { w.enableAlerts() }}>Enable</button></div>
            <div style={{ 'marginTop': '8px', 'fontSize': '11px', 'color': 'var(--dim)' }}>Alerts are checked live and fire desktop notifications + toasts.</div>
            <div className="al-list" id="alList"></div>
          </div>
        </div>
      </div>
      
      <div className="modal-overlay" id="thModal" role="dialog" aria-modal="true" aria-label="Color themes" onClick={(e) => { if(e.target=== e.currentTarget)w.closeModal('thModal') }}>
        <div className="modal-box" style={{ 'maxWidth': '560px' }}>
          <div className="modal-head">
            <div>Color Themes</div>
            <button className="modal-x" onClick={() => { w.closeModal('thModal') }}>X</button>
          </div>
          <div className="modal-body">
            <div style={{ 'fontSize': '12px', 'color': 'var(--muted)', 'marginBottom': '4px' }}>Pick a color combo — the whole interface (with dark &amp; light) follows. Your choice is saved automatically.</div>
            <div className="pal-grid" id="palGrid"></div>
          </div>
        </div>
      </div>
      
      
      

    </>
  )
}
